before_install: gem install bundler -v 1.14.3
cache: bundler
gemfile:
  - gemfiles/rails4.2.x.gemfile
  - gemfiles/rails5.x.gemfile
  - gemfiles/sinatra1.x.gemfile
language: ruby
matrix:
  fast_finish: true
notifications:
  email: false
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
sudo: false
